#pragma once
#if !defined(_EP_FOREACH_H)
#define _EP_FOREACH_H

#define EXPAND( X ) X

#define _NUM_ARGS2(X, X64,X63,X62,X61,X60,X59,X58,X57,X56,X55,X54,X53,X52,X51,X50,X49,X48,X47,X46,X45,X44,X43,X42,X41,X40,X39,X38,X37,X36,X35,X34,X33,X32,X31,X30,X29,X28,X27,X26,X25,X24,X23,X22,X21,X20,X19,X18,X17,X16,X15,X14,X13,X12,X11,X10,X9,X8,X7,X6,X5,X4,X3,X2,X1,N,...) N
#define NUM_ARGS(...) EXPAND( _NUM_ARGS2(0, __VA_ARGS__ ,64,63,62,61,60,59,58,57,56,55,54,53,52,51,50,49,48,47,46,45,44,43,42,41,40,39,38,37,36,35,34,33,32,31,30,29,28,27,26,25,24,23,22,21,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,0) )

#define FOR_EACH_1(DO, N, a)        DO(a, N-1)
#define FOR_EACH_2(DO, N, a,...)    EXPAND( DO(a, N-2) FOR_EACH_1(DO, N, __VA_ARGS__) )
#define FOR_EACH_3(DO, N, a,...)    EXPAND( DO(a, N-3) FOR_EACH_2(DO, N, __VA_ARGS__) )
#define FOR_EACH_4(DO, N, a,...)    EXPAND( DO(a, N-4) FOR_EACH_3(DO, N, __VA_ARGS__) )
#define FOR_EACH_5(DO, N, a,...)    EXPAND( DO(a, N-5) FOR_EACH_4(DO, N, __VA_ARGS__) )
#define FOR_EACH_6(DO, N, a,...)    EXPAND( DO(a, N-6) FOR_EACH_5(DO, N, __VA_ARGS__) )
#define FOR_EACH_7(DO, N, a,...)    EXPAND( DO(a, N-7) FOR_EACH_6(DO, N, __VA_ARGS__) )
#define FOR_EACH_8(DO, N, a,...)    EXPAND( DO(a, N-8) FOR_EACH_7(DO, N, __VA_ARGS__) )
#define FOR_EACH_9(DO, N, a,...)    EXPAND( DO(a, N-9) FOR_EACH_8(DO, N, __VA_ARGS__) )
#define FOR_EACH_10(DO, N, a,...)   EXPAND( DO(a, N-10) FOR_EACH_9(DO, N, __VA_ARGS__) )
#define FOR_EACH_11(DO, N, a,...)   EXPAND( DO(a, N-11) FOR_EACH_10(DO, N, __VA_ARGS__) )
#define FOR_EACH_12(DO, N, a,...)   EXPAND( DO(a, N-12) FOR_EACH_11(DO, N, __VA_ARGS__) )
#define FOR_EACH_13(DO, N, a,...)   EXPAND( DO(a, N-13) FOR_EACH_12(DO, N, __VA_ARGS__) )
#define FOR_EACH_14(DO, N, a,...)   EXPAND( DO(a, N-14) FOR_EACH_13(DO, N, __VA_ARGS__) )
#define FOR_EACH_15(DO, N, a,...)   EXPAND( DO(a, N-15) FOR_EACH_14(DO, N, __VA_ARGS__) )
#define FOR_EACH_16(DO, N, a,...)   EXPAND( DO(a, N-16) FOR_EACH_15(DO, N, __VA_ARGS__) )
#define FOR_EACH_17(DO, N, a,...)   EXPAND( DO(a, N-17) FOR_EACH_16(DO, N, __VA_ARGS__) )
#define FOR_EACH_18(DO, N, a,...)   EXPAND( DO(a, N-18) FOR_EACH_17(DO, N, __VA_ARGS__) )
#define FOR_EACH_19(DO, N, a,...)   EXPAND( DO(a, N-19) FOR_EACH_18(DO, N, __VA_ARGS__) )
#define FOR_EACH_20(DO, N, a,...)   EXPAND( DO(a, N-20) FOR_EACH_19(DO, N, __VA_ARGS__) )
#define FOR_EACH_21(DO, N, a,...)   EXPAND( DO(a, N-21) FOR_EACH_20(DO, N, __VA_ARGS__) )
#define FOR_EACH_22(DO, N, a,...)   EXPAND( DO(a, N-22) FOR_EACH_21(DO, N, __VA_ARGS__) )
#define FOR_EACH_23(DO, N, a,...)   EXPAND( DO(a, N-23) FOR_EACH_22(DO, N, __VA_ARGS__) )
#define FOR_EACH_24(DO, N, a,...)   EXPAND( DO(a, N-24) FOR_EACH_23(DO, N, __VA_ARGS__) )
#define FOR_EACH_25(DO, N, a,...)   EXPAND( DO(a, N-25) FOR_EACH_24(DO, N, __VA_ARGS__) )
#define FOR_EACH_26(DO, N, a,...)   EXPAND( DO(a, N-26) FOR_EACH_25(DO, N, __VA_ARGS__) )
#define FOR_EACH_27(DO, N, a,...)   EXPAND( DO(a, N-27) FOR_EACH_26(DO, N, __VA_ARGS__) )
#define FOR_EACH_28(DO, N, a,...)   EXPAND( DO(a, N-28) FOR_EACH_27(DO, N, __VA_ARGS__) )
#define FOR_EACH_29(DO, N, a,...)   EXPAND( DO(a, N-29) FOR_EACH_28(DO, N, __VA_ARGS__) )
#define FOR_EACH_30(DO, N, a,...)   EXPAND( DO(a, N-30) FOR_EACH_29(DO, N, __VA_ARGS__) )
#define FOR_EACH_31(DO, N, a,...)   EXPAND( DO(a, N-31) FOR_EACH_30(DO, N, __VA_ARGS__) )
#define FOR_EACH_32(DO, N, a,...)   EXPAND( DO(a, N-32) FOR_EACH_31(DO, N, __VA_ARGS__) )
#define FOR_EACH_33(DO, N, a,...)   EXPAND( DO(a, N-33) FOR_EACH_32(DO, N, __VA_ARGS__) )
#define FOR_EACH_34(DO, N, a,...)   EXPAND( DO(a, N-34) FOR_EACH_33(DO, N, __VA_ARGS__) )
#define FOR_EACH_35(DO, N, a,...)   EXPAND( DO(a, N-35) FOR_EACH_34(DO, N, __VA_ARGS__) )
#define FOR_EACH_36(DO, N, a,...)   EXPAND( DO(a, N-36) FOR_EACH_35(DO, N, __VA_ARGS__) )
#define FOR_EACH_37(DO, N, a,...)   EXPAND( DO(a, N-37) FOR_EACH_36(DO, N, __VA_ARGS__) )
#define FOR_EACH_38(DO, N, a,...)   EXPAND( DO(a, N-38) FOR_EACH_37(DO, N, __VA_ARGS__) )
#define FOR_EACH_39(DO, N, a,...)   EXPAND( DO(a, N-39) FOR_EACH_38(DO, N, __VA_ARGS__) )
#define FOR_EACH_40(DO, N, a,...)   EXPAND( DO(a, N-40) FOR_EACH_39(DO, N, __VA_ARGS__) )
#define FOR_EACH_41(DO, N, a,...)   EXPAND( DO(a, N-41) FOR_EACH_40(DO, N, __VA_ARGS__) )
#define FOR_EACH_42(DO, N, a,...)   EXPAND( DO(a, N-42) FOR_EACH_41(DO, N, __VA_ARGS__) )
#define FOR_EACH_43(DO, N, a,...)   EXPAND( DO(a, N-43) FOR_EACH_42(DO, N, __VA_ARGS__) )
#define FOR_EACH_44(DO, N, a,...)   EXPAND( DO(a, N-44) FOR_EACH_43(DO, N, __VA_ARGS__) )
#define FOR_EACH_45(DO, N, a,...)   EXPAND( DO(a, N-45) FOR_EACH_44(DO, N, __VA_ARGS__) )
#define FOR_EACH_46(DO, N, a,...)   EXPAND( DO(a, N-46) FOR_EACH_45(DO, N, __VA_ARGS__) )
#define FOR_EACH_47(DO, N, a,...)   EXPAND( DO(a, N-47) FOR_EACH_46(DO, N, __VA_ARGS__) )
#define FOR_EACH_48(DO, N, a,...)   EXPAND( DO(a, N-48) FOR_EACH_47(DO, N, __VA_ARGS__) )
#define FOR_EACH_49(DO, N, a,...)   EXPAND( DO(a, N-49) FOR_EACH_48(DO, N, __VA_ARGS__) )
#define FOR_EACH_50(DO, N, a,...)   EXPAND( DO(a, N-50) FOR_EACH_49(DO, N, __VA_ARGS__) )

#define _FOR_EACH_3(DO, N, ...) EXPAND( FOR_EACH_##N(DO, N, __VA_ARGS__) )
#define _FOR_EACH_2(DO, N, ...) EXPAND( _FOR_EACH_3(DO, N, __VA_ARGS__) )

#define FOR_EACH(DO, ...)       EXPAND( _FOR_EACH_2(DO, NUM_ARGS(__VA_ARGS__), __VA_ARGS__) )

#endif // _EP_FOREACH_H
