stages:
  - build
  - postbuild
  - package
  - rebuild_pending
  - clean

windows_shell_debug_64:
  stage: build
  script:
    - set QTDIR=C:\dev\Qt\5.6\msvc2015_64
    - set QTDIR32=C:\dev\Qt\5.6\msvc2015
    - "build\\build.sh epshell Debug x64 merge"
  tags:
    - windows
    - vs2015

windows_shell_release_64:
  stage: build
  script:
    - set QTDIR=C:\dev\Qt\5.6\msvc2015_64
    - set QTDIR32=C:\dev\Qt\5.6\msvc2015
    - "build\\build.sh epshell Release x64 merge"
  tags:
    - windows
    - vs2015

windows_shell_debug_32:
  stage: build
  script:
    - set QTDIR=C:\dev\Qt\5.6\msvc2015_64
    - set QTDIR32=C:\dev\Qt\5.6\msvc2015
    - "build\\build.sh epshell Debug win32 merge"
  tags:
    - windows
    - vs2015

windows_shell_release_32:
  stage: build
  script:
    - set QTDIR=C:\dev\Qt\5.6\msvc2015_64
    - set QTDIR32=C:\dev\Qt\5.6\msvc2015
    - "build\\build.sh epshell Release win32 merge"
  tags:
    - windows
    - vs2015

ubuntu_shell_debug_gcc:
  stage: build
  script:
    - export QTDIR=~/dev/Qt/5.6/gcc_64
    - "./build/build.sh epshell Debug x64 merge"
  tags:
    - linux
    - deb

ubuntu_shell_release_gcc:
  stage: build
  script:
    - export QTDIR=~/dev/Qt/5.6/gcc_64
    - "./build/build.sh epshell Release x64 merge"
  tags:
    - linux
    - deb

ubuntu_shell_debug_clang:
  stage: build
  script:
    - export QTDIR=~/dev/Qt/5.6/gcc_64
    - "./build/build.sh epshell DebugClang x64 merge"
  tags:
    - linux
    - deb

ubuntu_shell_release_clang:
  stage: build
  script:
    - export QTDIR=~/dev/Qt/5.6/gcc_64
    - "./build/build.sh epshell ReleaseClang x64 merge"
  tags:
    - linux
    - deb

rpm_shell_debug_gcc:
  stage: build
  script:
    - export QTDIR=~/dev/Qt/5.6/gcc_64
    - "./build/build.sh epshell Debug x64 merge"
  tags:
    - linux
    - rpm

rpm_shell_release_gcc:
  stage: build
  script:
    - export QTDIR=~/dev/Qt/5.6/gcc_64
    - "./build/build.sh epshell Release x64 merge"
  tags:
    - linux
    - rpm

rpm_shell_debug_clang:
  stage: build
  script:
    - export QTDIR=~/dev/Qt/5.6/gcc_64
    - "./build/build.sh epshell DebugClang x64 merge"
  tags:
    - linux
    - rpm

rpm_shell_release_clang:
  stage: build
  script:
    - export QTDIR=~/dev/Qt/5.6/gcc_64
    - "./build/build.sh epshell ReleaseClang x64 merge"
  tags:
    - linux
    - rpm

build_docs:
  stage: build
  only:
    - master
    - tags
  script: "build\\builddocs.sh"
  tags:
    - windows

collate_builds:
  stage: postbuild
  only:
    - master
    - tags
  script: "./build/collate.sh"
  tags:
    - ubuntu

windows_packaging:
  stage: package
  only:
    - master
    - tags
  script: "build\\packagewindows.sh"
  tags:
    - windows

update_merge_requests:
  stage: rebuild_pending
  script:
    - export QTDIR=~/dev/Qt/5.6/gcc_64
    - export PATH=$QTDIR/bin:$PATH
    - git submodule update --init --recursive
    - "bin/premake/premake5 --ci_project_id=$CI_PROJECT_ID --ci_build_ref_name=$CI_BUILD_REF_NAME --trigger_token=7b183a6a00a2405e30f5af529deb82 gitlab"
  tags:
    - linux

cleanup:
  stage: clean
  only:
    - master
    - tags
  when: always
  script: "./build/cleanup.sh"
  tags:
    - linux
