stages:
  - build
  - postbuild
  - dongleprotect
  - package
  - finalise
  - clean

windows_shell_debug_64:
  stage: build
  script:
    - set QTDIR=C:\dev\Qt\5.6\msvc2015_64
    - set QTDIR32=C:\dev\Qt\5.6\msvc2015
    - "build\\build.sh epshell Debug x64 merge"
  tags:
    - windows
    - vs2015

windows_shell_release_64:
  stage: build
  script:
    - set QTDIR=C:\dev\Qt\5.6\msvc2015_64
    - set QTDIR32=C:\dev\Qt\5.6\msvc2015
    - "build\\build.sh epshell Release x64 merge"
  tags:
    - windows
    - vs2015

windows_shell_debug_32:
  stage: build
  script:
    - set QTDIR=C:\dev\Qt\5.6\msvc2015_64
    - set QTDIR32=C:\dev\Qt\5.6\msvc2015
    - "build\\build.sh epshell Debug win32 merge"
  tags:
    - windows
    - vs2015

windows_shell_release_32:
  stage: build
  script:
    - set QTDIR=C:\dev\Qt\5.6\msvc2015_64
    - set QTDIR32=C:\dev\Qt\5.6\msvc2015
    - "build\\build.sh epshell Release win32 merge"
  tags:
    - windows
    - vs2015

ubuntu_shell_debug_gcc:
  stage: build
  script:
    - export QTDIR=~/dev/Qt/5.6/gcc_64
    - "./build/build.sh epshell Debug x64 merge"
  tags:
    - linux
    - deb

ubuntu_shell_release_gcc:
  stage: build
  script:
    - export QTDIR=~/dev/Qt/5.6/gcc_64
    - "./build/build.sh epshell Release x64 merge"
  tags:
    - linux
    - deb

ubuntu_shell_debug_clang:
  stage: build
  script:
    - export QTDIR=~/dev/Qt/5.6/gcc_64
    - "./build/build.sh epshell DebugClang x64 merge"
  tags:
    - linux
    - deb

ubuntu_shell_release_clang:
  stage: build
  script:
    - export QTDIR=~/dev/Qt/5.6/gcc_64
    - "./build/build.sh epshell ReleaseClang x64 merge"
  tags:
    - linux
    - deb

rpm_shell_debug_gcc:
  stage: build
  script:
    - export QTDIR=~/dev/Qt/5.6/gcc_64
    - "./build/build.sh epshell Debug x64 merge"
  tags:
    - linux
    - rpm

rpm_shell_release_gcc:
  stage: build
  script:
    - export QTDIR=~/dev/Qt/5.6/gcc_64
    - "./build/build.sh epshell Release x64 merge"
  tags:
    - linux
    - rpm

rpm_shell_debug_clang:
  stage: build
  script:
    - export QTDIR=~/dev/Qt/5.6/gcc_64
    - "./build/build.sh epshell DebugClang x64 merge"
  tags:
    - linux
    - rpm

rpm_shell_release_clang:
  stage: build
  script:
    - export QTDIR=~/dev/Qt/5.6/gcc_64
    - "./build/build.sh epshell ReleaseClang x64 merge"
  tags:
    - linux
    - rpm

build_docs:
  stage: build
  only:
    - master
    - tags
  script: "build\\builddocs.sh"
  tags:
    - windows

collate_builds:
  stage: postbuild
  only:
    - master
    - tags
  script: "./build/collate.sh"
  tags:
    - ubuntu

win64_dongleprotect:
  stage: dongleprotect
  only:
    - master
    - tags
  script: "build\\dongleprotectwindows.sh win64"
  tags:
    - windows

win32_dongleprotect:
  stage: dongleprotect
  only:
    - master
    - tags
  script: "build\\dongleprotectwindows.sh win32"
  tags:
    - windows

trusty_dongleprotect:
  stage: dongleprotect
  only:
    - master
    - tags
  script: "build\\dongleprotectlinux.sh trusty"
  tags:
    - windows

centos7_dongleprotect:
  stage: dongleprotect
  only:
    - master
    - tags
  script: "build\\dongleprotectlinux.sh centos7"
  tags:
    - windows

win64_packaging:
  stage: package
  only:
    - master
    - tags
  script: 
    - set QTDIR=C:\dev\Qt\5.6\msvc2015_64
    - "build\\packagewindows.sh win64"
  tags:
    - windows

win32_packaging:
  stage: package
  only:
    - master
    - tags
  script:
  - set QTDIR=C:\dev\Qt\5.6\msvc2015
  - "build\\packagewindows.sh win32"
  tags:
    - windows

trusty_packaging:
  stage: package
  only:
    - master
    - tags
  script:
    - export QTDIR=~/dev/Qt/5.6/gcc_64
    - ./build/packagelinux.sh trusty deb
  tags:
    - deb

centos7_packaging:
  stage: package
  only:
    - master
    - tags
  script:
    - export QTDIR=~/dev/Qt/5.6/gcc_64
    - ./build/packagelinux.sh centos7 rpm
  tags:
    - rpm

update_latest:
  stage: finalise
  only:
    - master
    - tags
  script: "./build/updatelatest.sh"
  tags:
    - linux

update_merge_requests:
  stage: finalise
  script:
    - export QTDIR=~/dev/Qt/5.6/gcc_64
    - export PATH=$QTDIR/bin:$PATH
    - git submodule update --init --recursive
    - "bin/premake/premake5 --ci_project_id=$CI_PROJECT_ID --ci_build_ref_name=$CI_BUILD_REF_NAME --trigger_token=7b183a6a00a2405e30f5af529deb82 gitlab"
  tags:
    - linux

cleanup:
  stage: clean
  only:
    - master
    - tags
  when: always
  script: "./build/cleanup.sh"
  tags:
    - linux
