stages:
  - build
  - postbuild
  - dongleprotect
  - package
  - finalise
  - clean

windows_shell_debug_64:
  stage: build
  script:
    - set QTDIR=C:\dev\Qt\5.6\msvc2015_64
    - set QTDIR32=C:\dev\Qt\5.6\msvc2015
    - "build\\build.sh epshell Debug x64 merge"
  tags:
    - windows
    - vs2015

windows_shell_releasedev_64:
  stage: build
  script:
    - set QTDIR=C:\dev\Qt\5.6\msvc2015_64
    - set QTDIR32=C:\dev\Qt\5.6\msvc2015
    - "build\\build.sh epshell ReleaseDev x64 merge"
  tags:
    - windows
    - vs2015

windows_shell_debug_32:
  stage: build
  script:
    - set QTDIR=C:\dev\Qt\5.6\msvc2015_64
    - set QTDIR32=C:\dev\Qt\5.6\msvc2015
    - "build\\build.sh epshell Debug win32 merge"
  tags:
    - windows
    - vs2015

windows_shell_releasedev_32:
  stage: build
  script:
    - set QTDIR=C:\dev\Qt\5.6\msvc2015_64
    - set QTDIR32=C:\dev\Qt\5.6\msvc2015
    - "build\\build.sh epshell ReleaseDev win32 merge"
  tags:
    - windows
    - vs2015

ubuntu_shell_debug_gcc:
  stage: build
  image: gitlab.euclideon.local:4567/docker-images/qt-xenial:5.6-v1
  script:
    - export QTDIR=~/dev/Qt/5.6/gcc_64
    - "./build/build.sh epshell Debug x64 merge"
  tags:
    - linux
    - docker

ubuntu_shell_releasedev_gcc:
  stage: build
  image: gitlab.euclideon.local:4567/docker-images/qt-xenial:5.6-v1
  script:
    - export QTDIR=~/dev/Qt/5.6/gcc_64
    - "./build/build.sh epshell ReleaseDev x64 merge"
  tags:
    - linux
    - docker

ubuntu_shell_debug_clang:
  stage: build
  image: gitlab.euclideon.local:4567/docker-images/qt-xenial:5.6-v1
  script:
    - export QTDIR=~/dev/Qt/5.6/gcc_64
    - "./build/build.sh epshell DebugClang x64 merge"
  tags:
    - linux
    - docker

ubuntu_shell_releasedev_clang:
  stage: build
  image: gitlab.euclideon.local:4567/docker-images/qt-xenial:5.6-v1
  script:
    - export QTDIR=~/dev/Qt/5.6/gcc_64
    - "./build/build.sh epshell ReleaseDevClang x64 merge"
  tags:
    - linux
    - docker

rpm_shell_debug_gcc:
  stage: build
  image: gitlab.euclideon.local:4567/docker-images/qt-centos7:5.6-v1
  script:
    - export QTDIR=~/dev/Qt/5.6/gcc_64
    - "./build/build.sh epshell Debug x64 merge"
  tags:
    - linux
    - docker

rpm_shell_releasedev_gcc:
  stage: build
  image: gitlab.euclideon.local:4567/docker-images/qt-centos7:5.6-v1
  script:
    - export QTDIR=~/dev/Qt/5.6/gcc_64
    - "./build/build.sh epshell ReleaseDev x64 merge"
  tags:
    - linux
    - docker

rpm_shell_debug_clang:
  stage: build
  image: gitlab.euclideon.local:4567/docker-images/qt-centos7:5.6-v1
  script:
    - export QTDIR=~/dev/Qt/5.6/gcc_64
    - "./build/build.sh epshell DebugClang x64 merge"
  tags:
    - linux
    - docker

rpm_shell_releasedev_clang:
  stage: build
  image: gitlab.euclideon.local:4567/docker-images/qt-centos7:5.6-v1
  script:
    - export QTDIR=~/dev/Qt/5.6/gcc_64
    - "./build/build.sh epshell ReleaseDevClang x64 merge"
  tags:
    - linux
    - docker

build_docs:
  stage: build
  only:
    - master
    - tags
  script: "build\\builddocs.sh"
  tags:
    - windows

collate_builds:
  stage: postbuild
  image: gitlab.euclideon.local:4567/docker-images/dev-xenial:v1
  only:
    - master
    - tags
  script: "./build/collate.sh"
  tags:
    - linux
    - docker

win64_dongleprotect:
  stage: dongleprotect
  only:
    - master
    - tags
  script: "build\\dongleprotectwindows.sh win64"
  tags:
    - windows

win32_dongleprotect:
  stage: dongleprotect
  only:
    - master
    - tags
  script: "build\\dongleprotectwindows.sh win32"
  tags:
    - windows

xenial_dongleprotect:
  stage: dongleprotect
  only:
    - master
    - tags
  script: "build\\dongleprotectlinux.sh xenial"
  tags:
    - windows

centos7_dongleprotect:
  stage: dongleprotect
  only:
    - master
    - tags
  script: "build\\dongleprotectlinux.sh centos7"
  tags:
    - windows

win64_packaging:
  stage: package
  only:
    - master
    - tags
  script:
    - set QTDIR=C:\dev\Qt\5.6\msvc2015_64
    - "build\\packagewindows.sh win64"
  tags:
    - windows

win32_packaging:
  stage: package
  only:
    - master
    - tags
  script:
  - set QTDIR=C:\dev\Qt\5.6\msvc2015
  - "build\\packagewindows.sh win32"
  tags:
    - windows

xenial_packaging:
  stage: package
  image: gitlab.euclideon.local:4567/docker-images/qt-xenial:5.6-v1
  only:
    - master
    - tags
  script:
    - export QTDIR=~/dev/Qt/5.6/gcc_64
    - ./build/packagelinux.sh xenial deb
  tags:
    - linux
    - docker

centos7_packaging:
  stage: package
  image: gitlab.euclideon.local:4567/docker-images/qt-centos7:5.6-v1
  only:
    - master
    - tags
  script:
    - export QTDIR=~/dev/Qt/5.6/gcc_64
    - ./build/packagelinux.sh centos7 rpm
  tags:
    - linux
    - docker

update_latest:
  stage: finalise
  image: gitlab.euclideon.local:4567/docker-images/dev-xenial:v1
  only:
    - master
    - tags
  script: "./build/updatelatest.sh"
  tags:
    - linux
    - docker

update_merge_requests:
  stage: finalise
  image: gitlab.euclideon.local:4567/docker-images/qt-xenial:5.6-v1
  script:
    - export QTDIR=~/dev/Qt/5.6/gcc_64
    - export PATH=$QTDIR/bin:$PATH
    - git submodule update --init --recursive
    - "bin/premake/premake5 --ci_project_id=$CI_PROJECT_ID --ci_build_ref_name=$CI_BUILD_REF_NAME --trigger_token=7b183a6a00a2405e30f5af529deb82 gitlab"
  tags:
    - linux
    - docker

cleanup:
  stage: clean
  image: gitlab.euclideon.local:4567/docker-images/dev-xenial:v1
  only:
    - master
    - tags
  when: always
  script: "./build/cleanup.sh"
  tags:
    - linux
    - docker
