#pragma once
#if !defined(_EP_FOREACH_H)
#define _EP_FOREACH_H

#define FOR_EACH_0(DO, N, ...)
#define FOR_EACH_1(DO, N, a)        DO(a, N-1)
#define FOR_EACH_2(DO, N, a,...)    EXPAND( DO(a, N-2) FOR_EACH_1(DO, N, __VA_ARGS__) )
#define FOR_EACH_3(DO, N, a,...)    EXPAND( DO(a, N-3) FOR_EACH_2(DO, N, __VA_ARGS__) )
#define FOR_EACH_4(DO, N, a,...)    EXPAND( DO(a, N-4) FOR_EACH_3(DO, N, __VA_ARGS__) )
#define FOR_EACH_5(DO, N, a,...)    EXPAND( DO(a, N-5) FOR_EACH_4(DO, N, __VA_ARGS__) )
#define FOR_EACH_6(DO, N, a,...)    EXPAND( DO(a, N-6) FOR_EACH_5(DO, N, __VA_ARGS__) )
#define FOR_EACH_7(DO, N, a,...)    EXPAND( DO(a, N-7) FOR_EACH_6(DO, N, __VA_ARGS__) )
#define FOR_EACH_8(DO, N, a,...)    EXPAND( DO(a, N-8) FOR_EACH_7(DO, N, __VA_ARGS__) )
#define FOR_EACH_9(DO, N, a,...)    EXPAND( DO(a, N-9) FOR_EACH_8(DO, N, __VA_ARGS__) )
#define FOR_EACH_10(DO, N, a,...)   EXPAND( DO(a, N-10) FOR_EACH_9(DO, N, __VA_ARGS__) )
#define FOR_EACH_11(DO, N, a,...)   EXPAND( DO(a, N-11) FOR_EACH_10(DO, N, __VA_ARGS__) )
#define FOR_EACH_12(DO, N, a,...)   EXPAND( DO(a, N-12) FOR_EACH_11(DO, N, __VA_ARGS__) )
#define FOR_EACH_13(DO, N, a,...)   EXPAND( DO(a, N-13) FOR_EACH_12(DO, N, __VA_ARGS__) )
#define FOR_EACH_14(DO, N, a,...)   EXPAND( DO(a, N-14) FOR_EACH_13(DO, N, __VA_ARGS__) )
#define FOR_EACH_15(DO, N, a,...)   EXPAND( DO(a, N-15) FOR_EACH_14(DO, N, __VA_ARGS__) )
#define FOR_EACH_16(DO, N, a,...)   EXPAND( DO(a, N-16) FOR_EACH_15(DO, N, __VA_ARGS__) )
#define FOR_EACH_17(DO, N, a,...)   EXPAND( DO(a, N-17) FOR_EACH_16(DO, N, __VA_ARGS__) )
#define FOR_EACH_18(DO, N, a,...)   EXPAND( DO(a, N-18) FOR_EACH_17(DO, N, __VA_ARGS__) )
#define FOR_EACH_19(DO, N, a,...)   EXPAND( DO(a, N-19) FOR_EACH_18(DO, N, __VA_ARGS__) )
#define FOR_EACH_20(DO, N, a,...)   EXPAND( DO(a, N-20) FOR_EACH_19(DO, N, __VA_ARGS__) )
#define FOR_EACH_21(DO, N, a,...)   EXPAND( DO(a, N-21) FOR_EACH_20(DO, N, __VA_ARGS__) )
#define FOR_EACH_22(DO, N, a,...)   EXPAND( DO(a, N-22) FOR_EACH_21(DO, N, __VA_ARGS__) )
#define FOR_EACH_23(DO, N, a,...)   EXPAND( DO(a, N-23) FOR_EACH_22(DO, N, __VA_ARGS__) )
#define FOR_EACH_24(DO, N, a,...)   EXPAND( DO(a, N-24) FOR_EACH_23(DO, N, __VA_ARGS__) )
#define FOR_EACH_25(DO, N, a,...)   EXPAND( DO(a, N-25) FOR_EACH_24(DO, N, __VA_ARGS__) )
#define FOR_EACH_26(DO, N, a,...)   EXPAND( DO(a, N-26) FOR_EACH_25(DO, N, __VA_ARGS__) )
#define FOR_EACH_27(DO, N, a,...)   EXPAND( DO(a, N-27) FOR_EACH_26(DO, N, __VA_ARGS__) )
#define FOR_EACH_28(DO, N, a,...)   EXPAND( DO(a, N-28) FOR_EACH_27(DO, N, __VA_ARGS__) )
#define FOR_EACH_29(DO, N, a,...)   EXPAND( DO(a, N-29) FOR_EACH_28(DO, N, __VA_ARGS__) )
#define FOR_EACH_30(DO, N, a,...)   EXPAND( DO(a, N-30) FOR_EACH_29(DO, N, __VA_ARGS__) )
#define FOR_EACH_31(DO, N, a,...)   EXPAND( DO(a, N-31) FOR_EACH_30(DO, N, __VA_ARGS__) )
#define FOR_EACH_32(DO, N, a,...)   EXPAND( DO(a, N-32) FOR_EACH_31(DO, N, __VA_ARGS__) )
#define FOR_EACH_33(DO, N, a,...)   EXPAND( DO(a, N-33) FOR_EACH_32(DO, N, __VA_ARGS__) )
#define FOR_EACH_34(DO, N, a,...)   EXPAND( DO(a, N-34) FOR_EACH_33(DO, N, __VA_ARGS__) )
#define FOR_EACH_35(DO, N, a,...)   EXPAND( DO(a, N-35) FOR_EACH_34(DO, N, __VA_ARGS__) )
#define FOR_EACH_36(DO, N, a,...)   EXPAND( DO(a, N-36) FOR_EACH_35(DO, N, __VA_ARGS__) )
#define FOR_EACH_37(DO, N, a,...)   EXPAND( DO(a, N-37) FOR_EACH_36(DO, N, __VA_ARGS__) )
#define FOR_EACH_38(DO, N, a,...)   EXPAND( DO(a, N-38) FOR_EACH_37(DO, N, __VA_ARGS__) )
#define FOR_EACH_39(DO, N, a,...)   EXPAND( DO(a, N-39) FOR_EACH_38(DO, N, __VA_ARGS__) )
#define FOR_EACH_40(DO, N, a,...)   EXPAND( DO(a, N-40) FOR_EACH_39(DO, N, __VA_ARGS__) )
#define FOR_EACH_41(DO, N, a,...)   EXPAND( DO(a, N-41) FOR_EACH_40(DO, N, __VA_ARGS__) )
#define FOR_EACH_42(DO, N, a,...)   EXPAND( DO(a, N-42) FOR_EACH_41(DO, N, __VA_ARGS__) )
#define FOR_EACH_43(DO, N, a,...)   EXPAND( DO(a, N-43) FOR_EACH_42(DO, N, __VA_ARGS__) )
#define FOR_EACH_44(DO, N, a,...)   EXPAND( DO(a, N-44) FOR_EACH_43(DO, N, __VA_ARGS__) )
#define FOR_EACH_45(DO, N, a,...)   EXPAND( DO(a, N-45) FOR_EACH_44(DO, N, __VA_ARGS__) )
#define FOR_EACH_46(DO, N, a,...)   EXPAND( DO(a, N-46) FOR_EACH_45(DO, N, __VA_ARGS__) )
#define FOR_EACH_47(DO, N, a,...)   EXPAND( DO(a, N-47) FOR_EACH_46(DO, N, __VA_ARGS__) )
#define FOR_EACH_48(DO, N, a,...)   EXPAND( DO(a, N-48) FOR_EACH_47(DO, N, __VA_ARGS__) )
#define FOR_EACH_49(DO, N, a,...)   EXPAND( DO(a, N-49) FOR_EACH_48(DO, N, __VA_ARGS__) )
#define FOR_EACH_50(DO, N, a,...)   EXPAND( DO(a, N-50) FOR_EACH_49(DO, N, __VA_ARGS__) )

#define _FOR_EACH_3(DO, N, ...) EXPAND( FOR_EACH_##N(DO, N, __VA_ARGS__) )
#define _FOR_EACH_2(DO, N, ...) EXPAND( _FOR_EACH_3(DO, N, __VA_ARGS__) )

#define FOR_EACH(DO, ...)       EXPAND( _FOR_EACH_2(DO, NUM_ARGS(__VA_ARGS__), __VA_ARGS__) )

#endif // _EP_FOREACH_H
