#pragma once
#if !defined(UD_GLUT)
#define UD_GLUT

#include "udViewerPlatform.h"

#if UDWINDOW_DRIVER == UDDRIVER_GLUT

#pragma warning(disable:4505) //  unreferenced local function has been removed - a warning generated by freeglut

#define FREEGLUT_STATIC
#define FREEGLUT_LIB_PRAGMAS 0
#include "GL/freeglut.h"

#endif // UDRENDER_DRIVER == UDDRIVER_GLUT
#endif // UD_GLUT
