#pragma once
#ifndef UDVIEWERPLATFORM_H
#define UDVIEWERPLATFORM_H

#include "udPlatform.h"

#define UDDRIVER_OPENGL 100
#define UDDRIVER_GLUT   101
#define UDDRIVER_SDL    102
#define UDDRIVER_PPAPI  103
#define UDDRIVER_QT     104

#if UDPLATFORM_WINDOWS
# define UDWINDOW_DRIVER UDDRIVER_GLUT
# define UDRENDER_DRIVER UDDRIVER_OPENGL
# define UDINPUT_DRIVER  UDDRIVER_GLUT
#elif UDPLATFORM_LINUX
# define UDWINDOW_DRIVER UDDRIVER_GLUT
# define UDRENDER_DRIVER UDDRIVER_OPENGL
# define UDINPUT_DRIVER  UDDRIVER_GLUT
#elif UDPLATFORM_NACL
# define UDWINDOW_DRIVER UDDRIVER_PPAPI
# define UDRENDER_DRIVER UDDRIVER_OPENGL
# define UDINPUT_DRIVER  UDDRIVER_PPAPI

# define USE_GLES
#endif

#endif // UDVIEWERPLATFORM_H
