#pragma once
#ifndef UDVIEWERPLATFORM_H
#define UDVIEWERPLATFORM_H

#include "udPlatform.h"

#define UDDRIVER_NULL   100
#define UDDRIVER_OPENGL 101
#define UDDRIVER_GLUT   102
#define UDDRIVER_SDL    103
#define UDDRIVER_PPAPI  104
#define UDDRIVER_QT     105

#if UD_USE_QT
# define UDWINDOW_DRIVER UDDRIVER_QT
# define UDRENDER_DRIVER UDDRIVER_QT
# define UDINPUT_DRIVER  UDDRIVER_QT
#elif UDPLATFORM_WINDOWS
# define UDWINDOW_DRIVER UDDRIVER_SDL
# define UDRENDER_DRIVER UDDRIVER_OPENGL
# define UDINPUT_DRIVER  UDDRIVER_SDL
# define USE_GLEW
#elif UDPLATFORM_LINUX
# define UDWINDOW_DRIVER UDDRIVER_SDL
# define UDRENDER_DRIVER UDDRIVER_OPENGL
# define UDINPUT_DRIVER  UDDRIVER_SDL
# define USE_GLEW
#elif UDPLATFORM_NACL
# define UDWINDOW_DRIVER UDDRIVER_PPAPI
# define UDRENDER_DRIVER UDDRIVER_OPENGL
# define UDINPUT_DRIVER  UDDRIVER_PPAPI
#elif UDPLATFORM_NULL
# define UDWINDOW_DRIVER UDDRIVER_NULL
# define UDRENDER_DRIVER UDDRIVER_NULL
# define UDINPUT_DRIVER  UDDRIVER_NULL
#endif

#endif // UDVIEWERPLATFORM_H
