#pragma once
#ifndef EP_DRIVER_H
#define EP_DRIVER_H

#include "ep/epplatform.h"

#define EPDRIVER_NULL   100
#define EPDRIVER_OPENGL 101
#define EPDRIVER_GLUT   102
#define EPDRIVER_SDL    103
#define EPDRIVER_PPAPI  104
#define EPDRIVER_QT     105
#define EPDRIVER_WIN32  106

#if EP_USE_QT
# define EPWINDOW_DRIVER EPDRIVER_QT
# define EPRENDER_DRIVER EPDRIVER_QT
# define EPINPUT_DRIVER  EPDRIVER_QT
# define EPUI_DRIVER     EPDRIVER_QT
# if defined(EP_WINDOWS)
#   define EPIMAGE_DRIVER  EPDRIVER_WIN32
# else
#   define EPIMAGE_DRIVER  EPDRIVER_NULL
# endif
#elif defined(EP_WINDOWS)
# define EPWINDOW_DRIVER EPDRIVER_SDL
# define EPRENDER_DRIVER EPDRIVER_OPENGL
# define EPINPUT_DRIVER  EPDRIVER_SDL
# define EPUI_DRIVER     EPDRIVER_NULL
# define EPIMAGE_DRIVER  EPDRIVER_WIN32
# define USE_GLEW
#elif defined(EP_LINUX)
# define EPWINDOW_DRIVER EPDRIVER_SDL
# define EPRENDER_DRIVER EPDRIVER_OPENGL
# define EPINPUT_DRIVER  EPDRIVER_SDL
# define EPUI_DRIVER     EPDRIVER_NULL
# define EPIMAGE_DRIVER  EPDRIVER_NULL
# define USE_GLEW
#elif defined(EP_NACL)
# define EPWINDOW_DRIVER EPDRIVER_PPAPI
# define EPRENDER_DRIVER EPDRIVER_OPENGL
# define EPINPUT_DRIVER  EPDRIVER_PPAPI
# define EPUI_DRIVER     EPDRIVER_NULL
# define EPIMAGE_DRIVER  EPDRIVER_NULL
#elif defined(EP_NULL)
# define EPWINDOW_DRIVER EPDRIVER_NULL
# define EPRENDER_DRIVER EPDRIVER_NULL
# define EPINPUT_DRIVER  EPDRIVER_NULL
# define EPUI_DRIVER     EPDRIVER_NULL
# define EPIMAGE_DRIVER  EPDRIVER_NULL
#endif

#endif // EP_DRIVER_H
