#pragma once
#ifndef UDVIEWERPLATFORM_H
#define UDVIEWERPLATFORM_H

#include "udPlatform.h"

#define UDDRIVER_NULL   100
#define UDDRIVER_OPENGL 101
#define UDDRIVER_GLUT   102
#define UDDRIVER_SDL    103
#define UDDRIVER_PPAPI  104
#define UDDRIVER_QT     105
#define UDDRIVER_WIN32  106

#if EP_USE_QT
# define UDWINDOW_DRIVER UDDRIVER_QT
# define UDRENDER_DRIVER UDDRIVER_QT
# define UDINPUT_DRIVER  UDDRIVER_QT
# define UDUI_DRIVER     UDDRIVER_QT
# if UDPLATFORM_WINDOWS
#   define UDIMAGE_DRIVER  UDDRIVER_WIN32
# else
#   define UDIMAGE_DRIVER  UDDRIVER_NULL
# endif
#elif UDPLATFORM_WINDOWS
# define UDWINDOW_DRIVER UDDRIVER_SDL
# define UDRENDER_DRIVER UDDRIVER_OPENGL
# define UDINPUT_DRIVER  UDDRIVER_SDL
# define UDUI_DRIVER     UDDRIVER_NULL
# define UDIMAGE_DRIVER  UDDRIVER_WIN32
# define USE_GLEW
#elif UDPLATFORM_LINUX
# define UDWINDOW_DRIVER UDDRIVER_SDL
# define UDRENDER_DRIVER UDDRIVER_OPENGL
# define UDINPUT_DRIVER  UDDRIVER_SDL
# define UDUI_DRIVER     UDDRIVER_NULL
# define UDIMAGE_DRIVER  UDDRIVER_NULL
# define USE_GLEW
#elif UDPLATFORM_NACL
# define UDWINDOW_DRIVER UDDRIVER_PPAPI
# define UDRENDER_DRIVER UDDRIVER_OPENGL
# define UDINPUT_DRIVER  UDDRIVER_PPAPI
# define UDUI_DRIVER     UDDRIVER_NULL
# define UDIMAGE_DRIVER  UDDRIVER_NULL
#elif UDPLATFORM_NULL
# define UDWINDOW_DRIVER UDDRIVER_NULL
# define UDRENDER_DRIVER UDDRIVER_NULL
# define UDINPUT_DRIVER  UDDRIVER_NULL
# define UDUI_DRIVER     UDDRIVER_NULL
# define UDIMAGE_DRIVER  UDDRIVER_NULL
#endif

#endif // UDVIEWERPLATFORM_H
